version: '2'
services:
  emotions-app:
    image: emotions
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://emotions-postgresql:5432/emotions
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 80:80
  emotions-postgresql:
    extends:
      file: postgresql.yml
      service: emotions-postgresql
